package logstorage

import (
	"fmt"
)

// filterPatternMatch filters field entries by the given pattern, which could be generated by collapse_nums pipe.
//
// See https://docs.victoriametrics.com/victorialogs/logsql/#collapse_nums-pipe
type filterPatternMatch struct {
	funcName string
	pm       *patternMatcher
}

func newFilterPatternMatch(fieldName, funcName string, pm *patternMatcher) *filterGeneric {
	fp := &filterPatternMatch{
		funcName: funcName,
		pm:       pm,
	}
	return newFilterGeneric(fieldName, fp)
}

func (fp *filterPatternMatch) String() string {
	return fmt.Sprintf("%s(%s)", fp.funcName, quoteTokenIfNeeded(fp.pm.String()))
}
