package logstorage

import (
	"fmt"
	"strings"
	"sync"

	"github.com/VictoriaMetrics/VictoriaMetrics/lib/logger"

	"github.com/VictoriaMetrics/VictoriaLogs/lib/prefixfilter"
)

// PipeStats processes '| stats ...' queries.
//
// See https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe
type PipeStats struct {
	// byFields contains field names with optional buckets from 'by(...)' clause.
	byFields []*byStatsField

	// entries contains parsed entries from stats pipe.
	entries []pipeStatsEntry

	// funcs contains stats functions to execute.
	//
	// funcs are generated from entries via appendToFuncs call.
	funcs []pipeStatsFunc

	mode pipeStatsMode
}

func (p *PipeStats) ByFields() []*byStatsField {
	return p.byFields
}

func (p *PipeStats) Funcs() []pipeStatsFunc {
	return p.funcs
}

type pipeStatsMode int

func (psm pipeStatsMode) needImportState() bool {
	switch psm {
	case pipeStatsModeLocal, pipeStatsModeProxy:
		return true
	default:
		return false
	}
}

const (
	pipeStatsModeDefault = pipeStatsMode(0)
	pipeStatsModeRemote  = pipeStatsMode(1)
	pipeStatsModeLocal   = pipeStatsMode(2)
	pipeStatsModeProxy   = pipeStatsMode(3)
)

type pipeStatsEntry interface {
	String() string

	appendToFuncs(dst []pipeStatsFunc) []pipeStatsFunc
}

type pipeStatsSwitch struct {
	f statsFunc

	cases []pipeStatsCase
}

func (sw *pipeStatsSwitch) String() string {
	s := sw.f.String()

	a := make([]string, len(sw.cases))
	for i, c := range sw.cases {
		a[i] = c.String()
	}
	s += " switch(" + strings.Join(a, ", ") + ")"

	return s
}

func (sw *pipeStatsSwitch) appendToFuncs(dst []pipeStatsFunc) []pipeStatsFunc {
	for _, c := range sw.cases {
		iff := c.iff
		if iff == nil {
			iff = sw.getDefaultFilter()
		}
		dst = append(dst, pipeStatsFunc{
			f:          sw.f,
			iff:        iff,
			resultName: c.resultName,
		})
	}

	return dst
}

func (sw *pipeStatsSwitch) getDefaultFilter() *ifFilter {
	var filters []filter
	for _, c := range sw.cases {
		if c.iff != nil {
			filters = append(filters, c.iff.f)
		}
	}

	if len(filters) == 0 {
		return newIfFilter(newFilterNoop())
	}

	filter := newFilterNot(newFilterOr(filters))
	return newIfFilter(filter)
}

type pipeStatsCase struct {
	iff        *ifFilter
	resultName string
}

func (c *pipeStatsCase) String() string {
	if c.iff == nil {
		return "default as " + quoteTokenIfNeeded(c.resultName)
	}
	return fmt.Sprintf("case (%s) as %s", c.iff.f.String(), quoteTokenIfNeeded(c.resultName))
}

type pipeStatsFunc struct {
	// f is stats function to execute
	f statsFunc

	// iff is an additional filter, which is applied to results before executing f on them
	iff *ifFilter

	// resultName is the name of the output generated by f
	resultName string
}

func (f *pipeStatsFunc) Func() statsFunc {
	return f.f
}

func (f *pipeStatsFunc) IfFilter() *ifFilter {
	return f.iff
}

func (f *pipeStatsFunc) ResultName() string {
	return f.resultName
}

func (f *pipeStatsFunc) String() string {
	s := f.f.String()
	if f.iff != nil {
		s += " " + f.iff.String()
	}
	s += " as " + quoteTokenIfNeeded(f.resultName)
	return s
}

func (f *pipeStatsFunc) appendToFuncs(dst []pipeStatsFunc) []pipeStatsFunc {
	return append(dst, *f)
}

type statsFunc interface {
	Name() string

	// String returns string representation of statsFunc
	String() string

	// updateNeededFields must update pf with the fields needed for calculating the given stats
	updateNeededFields(pf *prefixfilter.Filter)
}

func (ps *PipeStats) String() string {
	s := ps.Name()
	byFields := ps.byFields
	if len(byFields) > 0 {
		a := make([]string, len(byFields))
		for i := range byFields {
			a[i] = byFields[i].String()
		}
		s += " by (" + strings.Join(a, ", ") + ")"
	}

	if ps.mode.needImportState() {
		if len(ps.funcs) == 0 {
			logger.Panicf("BUG: pipeStats must contain at least a single func")
		}
		a := make([]string, len(ps.funcs))
		for i, f := range ps.funcs {
			resultNameQuoted := quoteTokenIfNeeded(f.resultName)
			a[i] = fmt.Sprintf("import_state(%s) as %s", resultNameQuoted, resultNameQuoted)
		}
		s += " " + strings.Join(a, ", ")
	} else {
		if len(ps.entries) == 0 {
			logger.Panicf("BUG: pipeStats must contain at least a single entry")
		}
		a := make([]string, len(ps.entries))
		for i, e := range ps.entries {
			a[i] = e.String()
		}
		s += " " + strings.Join(a, ", ")
	}
	return s
}

func (ps *PipeStats) Name() string {
	switch ps.mode {
	case pipeStatsModeDefault:
		return "stats"
	case pipeStatsModeRemote:
		return "stats_remote"
	case pipeStatsModeLocal:
		return "stats_local"
	case pipeStatsModeProxy:
		return "stats_proxy"
	default:
		logger.Panicf("BUG: unknown mode: %d", ps.mode)
	}
	return ""
}

func (ps *PipeStats) updateNeededFields(pf *prefixfilter.Filter) {
	if ps.mode.needImportState() {
		ps.updateNeededFieldsLocal(pf)
		return
	}

	pfOrig := pf.Clone()
	pf.Reset()

	for _, f := range ps.funcs {
		if pfOrig.MatchString(f.resultName) {
			f.f.updateNeededFields(pf)
			if f.iff != nil {
				pf.AddAllowFilters(f.iff.allowFilters)
			}
		}
	}

	// byFields are needed unconditionally, since the output number of rows depends on them.
	for _, bf := range ps.byFields {
		pf.AddAllowFilter(bf.name)
	}
}

func (ps *PipeStats) updateNeededFieldsLocal(pf *prefixfilter.Filter) {
	pf.Reset()

	for _, bf := range ps.byFields {
		pf.AddAllowFilter(bf.name)
	}
	for _, f := range ps.funcs {
		pf.AddAllowFilter(f.resultName)
	}
}

func (ps *PipeStats) visitSubqueries(visitFunc func(q *Query)) {
	for _, f := range ps.funcs {
		f.iff.visitSubqueries(visitFunc)
	}
}

func (ps *PipeStats) initRateFuncs(step int64) {
	if step <= 0 {
		return
	}

	stepSeconds := float64(step) / 1e9
	for _, f := range ps.funcs {
		switch t := f.f.(type) {
		case *statsRate:
			t.stepSeconds = stepSeconds
		case *statsRateSum:
			t.stepSeconds = stepSeconds
		}
	}
}

func parsePipeStats(lex *lexer) (pipe, error) {
	return parsePipeStatsExt(lex, true)
}

func parsePipeStatsNoStatsKeyword(lex *lexer) (pipe, error) {
	return parsePipeStatsExt(lex, false)
}

func parsePipeStatsExt(lex *lexer, needStatsKeyword bool) (pipe, error) {
	var ps PipeStats
	if needStatsKeyword {
		switch {
		case lex.isKeyword("stats"):
			lex.nextToken()
			ps.mode = pipeStatsModeDefault
		case lex.isKeyword("stats_remote"):
			lex.nextToken()
			ps.mode = pipeStatsModeRemote
		default:
			return nil, fmt.Errorf("expecting 'stats' or 'stats_remote'; got %q", lex.token)
		}
	}

	if lex.isKeyword("by", "(") {
		if lex.isKeyword("by") {
			lex.nextToken()
		}
		bfs, err := parseByStatsFields(lex)
		if err != nil {
			return nil, fmt.Errorf("cannot parse 'by' clause: %w", err)
		}
		ps.byFields = bfs
	}

	seenByFields := make(map[string]*byStatsField, len(ps.byFields))
	for _, bf := range ps.byFields {
		seenByFields[bf.name] = bf
	}

	for {
		e, err := parseStatsEntry(lex)
		if err != nil {
			return nil, fmt.Errorf("cannot parse 'stats' entry: %w", err)
		}
		ps.entries = append(ps.entries, e)

		if lex.isKeyword("|", ")", "") {
			break
		}
		if !lex.isKeyword(",") {
			return nil, fmt.Errorf("unexpected token %q after [%s]; want ',', '|' or ')'", lex.token, e)
		}
		lex.nextToken()
	}

	for _, e := range ps.entries {
		ps.funcs = e.appendToFuncs(ps.funcs)
	}
	if len(ps.funcs) == 0 {
		return nil, fmt.Errorf("'stats' pipe must contain at least a single entry")
	}

	seenResultNames := make(map[string]statsFunc)
	for _, f := range ps.funcs {
		if bf := seenByFields[f.resultName]; bf != nil {
			return nil, fmt.Errorf("the %q is used as 'by' field [%s], so it cannot be used as result name for [%s]", f.resultName, bf, f.f)
		}
		if sfPrev := seenResultNames[f.resultName]; sfPrev != nil {
			return nil, fmt.Errorf("cannot use identical result name %q for [%s] and [%s]", f.resultName, sfPrev, f.f)
		}
		seenResultNames[f.resultName] = f.f
	}

	return &ps, nil
}

func parseStatsEntry(lex *lexer) (pipeStatsEntry, error) {
	sf, err := parseStatsFunc(lex)
	if err != nil {
		return nil, err
	}

	if lex.isKeyword("switch") {
		sw, err := parseStatsSwitch(lex, sf)
		if err != nil {
			return nil, fmt.Errorf("cannot parse 'switch' for [%s]: %w", sf, err)
		}
		return sw, nil
	}

	var iff *ifFilter
	if lex.isKeyword("if") {
		iff, err = parseIfFilter(lex)
		if err != nil {
			return nil, fmt.Errorf("cannot parse 'if' filter for [%s]: %w", sf, err)
		}
	}

	resultName := ""
	if lex.isKeyword(",", "|", ")", "") {
		resultName = sf.String()
		if iff != nil {
			resultName += " " + iff.String()
		}
	} else {
		if lex.isKeyword("as") {
			lex.nextToken()
		}
		fieldName, err := parseFieldName(lex)
		if err != nil {
			return nil, fmt.Errorf("cannot parse result name for [%s]: %w", sf, err)
		}
		resultName = fieldName
	}

	return &pipeStatsFunc{
		f:          sf,
		iff:        iff,
		resultName: resultName,
	}, nil
}

func parseStatsSwitch(lex *lexer, sf statsFunc) (*pipeStatsSwitch, error) {
	if !lex.isKeyword("switch") {
		return nil, fmt.Errorf("missing 'switch' keyword")
	}
	lex.nextToken()

	if !lex.isKeyword("(") {
		return nil, fmt.Errorf("missing '(' after the 'switch'")
	}
	lex.nextToken()

	var cases []pipeStatsCase
	defaultSet := false
	for !lex.isKeyword(")") {
		switch {
		case lex.isKeyword("case", "if"):
			iff, err := parseIfFilter(lex)
			if err != nil {
				return nil, fmt.Errorf("cannot parse case filter: %w", err)
			}
			if lex.isKeyword("as") {
				lex.nextToken()
			}
			resultName, err := parseFieldName(lex)
			if err != nil {
				return nil, fmt.Errorf("cannot parse result name for the case (%s): %w", iff.f, err)
			}
			cases = append(cases, pipeStatsCase{
				iff:        iff,
				resultName: resultName,
			})
		case lex.isKeyword("default"):
			if defaultSet {
				return nil, fmt.Errorf("switch(...) cannot contain more than one 'default'")
			}
			defaultSet = true
			lex.nextToken()
			if lex.isKeyword("as") {
				lex.nextToken()
			}
			resultName, err := parseFieldName(lex)
			if err != nil {
				return nil, fmt.Errorf("cannot parse result name for the default case: %w", err)
			}
			cases = append(cases, pipeStatsCase{
				resultName: resultName,
			})
		default:
			return nil, fmt.Errorf("unexpected token inside switch(...): %q; want 'case' or 'default'", lex.token)
		}

		if !lex.isKeyword(",", ")") {
			return nil, fmt.Errorf("unexpected token after %s: %q; want ',' or ')'", &cases[len(cases)-1], lex.token)
		}
		if lex.isKeyword(",") {
			lex.nextToken()
		}
	}
	if len(cases) == 0 {
		return nil, fmt.Errorf("switch(...) must contain at least a single 'case' or 'default'")
	}
	lex.nextToken()

	return &pipeStatsSwitch{
		f:     sf,
		cases: cases,
	}, nil
}

func parseStatsFunc(lex *lexer) (statsFunc, error) {
	sps := getStatsFuncParsers()
	for funcName, parserFunc := range sps {
		if !lex.isKeyword(funcName) {
			continue
		}
		sf, err := parserFunc(lex)
		if err != nil {
			return nil, fmt.Errorf("cannot parse %q func: %w", funcName, err)
		}
		return sf, nil
	}
	return nil, fmt.Errorf("unknown stats func %q", lex.token)
}

var statsFuncParsers map[string]statsFuncParser
var statsFuncParsersOnce sync.Once

type statsFuncParser func(lex *lexer) (statsFunc, error)

func getStatsFuncParsers() map[string]statsFuncParser {
	statsFuncParsersOnce.Do(initStatsFuncParsers)
	return statsFuncParsers
}

func initStatsFuncParsers() {
	statsFuncParsers = map[string]statsFuncParser{
		"any":             parseStatsAny,
		"avg":             parseStatsAvg,
		"count":           parseStatsCount,
		"count_empty":     parseStatsCountEmpty,
		"count_uniq":      parseStatsCountUniq,
		"count_uniq_hash": parseStatsCountUniqHash,
		"field_max":       parseStatsFieldMax,
		"field_min":       parseStatsFieldMin,
		"histogram":       parseStatsHistogram,
		"json_values":     parseStatsJSONValues,
		"max":             parseStatsMax,
		"median":          parseStatsMedian,
		"min":             parseStatsMin,
		"quantile":        parseStatsQuantile,
		"rate":            parseStatsRate,
		"rate_sum":        parseStatsRateSum,
		"row_any":         parseStatsRowAny,
		"row_max":         parseStatsRowMax,
		"row_min":         parseStatsRowMin,
		"stddev":          parseStatsStddev,
		"sum":             parseStatsSum,
		"sum_len":         parseStatsSumLen,
		"uniq_values":     parseStatsUniqValues,
		"values":          parseStatsValues,
	}
}

func isStatsFuncName(s string) bool {
	sps := getStatsFuncParsers()
	sLower := strings.ToLower(s)
	return sps[sLower] != nil
}

// byStatsField represents 'by (...)' part of the pipeStats.
//
// It can have either 'name' representation or 'name:bucket' or 'name:bucket offset off' representation,
// where `bucket` and `off` can contain duration, size or numeric value for creating different buckets
// for 'value/bucket'.
type byStatsField struct {
	name string

	// bucketSizeStr is string representation of the bucket size
	bucketSizeStr string

	// bucketSize is the bucket for grouping the given field values with value/bucketSize calculations
	bucketSize float64

	// bucketOffsetStr is string representation of the offset for bucketSize
	bucketOffsetStr string

	// bucketOffset is the offset for bucketSize
	bucketOffset float64
}

func (bf *byStatsField) Name() string {
	return bf.name
}

func (bf *byStatsField) String() string {
	s := quoteTokenIfNeeded(bf.name)
	if bf.bucketSizeStr != "" {
		s += ":" + bf.bucketSizeStr
		if bf.bucketOffsetStr != "" {
			s += " offset " + bf.bucketOffsetStr
		}
	}
	return s
}

func parseByStatsFields(lex *lexer) ([]*byStatsField, error) {
	if !lex.isKeyword("(") {
		return nil, fmt.Errorf("missing `(`")
	}
	var bfs []*byStatsField
	for {
		lex.nextToken()
		if lex.isKeyword(")") {
			lex.nextToken()
			return bfs, nil
		}
		fieldName, err := lex.nextCompoundTokenExt([]string{":"})
		if err != nil {
			return nil, fmt.Errorf("cannot parse field name: %w", err)
		}
		fieldName = getCanonicalColumnName(fieldName)
		bf := &byStatsField{
			name: fieldName,
		}
		if lex.isKeyword(":") {
			// Parse bucket size
			lex.nextToken()

			bucketSizeStr, err := lex.nextCompoundToken()
			if err != nil {
				return nil, fmt.Errorf("cannot parse bucket size for field %q: %w", fieldName, err)
			}
			if bucketSizeStr != "year" && bucketSizeStr != "month" {
				bucketSize, ok := tryParseBucketSize(bucketSizeStr)
				if !ok {
					return nil, fmt.Errorf("cannot parse bucket size for field %q: %q", fieldName, bucketSizeStr)
				}
				bf.bucketSize = bucketSize
			}
			bf.bucketSizeStr = bucketSizeStr

			// Parse bucket offset
			if lex.isKeyword("offset") {
				lex.nextToken()

				bucketOffsetStr, err := lex.nextCompoundToken()
				if err != nil {
					return nil, fmt.Errorf("cannot parse offset token for %q: %w", fieldName, err)
				}

				bucketOffset, ok := tryParseBucketOffset(bucketOffsetStr)
				if !ok {
					return nil, fmt.Errorf("cannot parse bucket offset for field %q: %q", fieldName, bucketOffsetStr)
				}
				bf.bucketOffsetStr = bucketOffsetStr
				bf.bucketOffset = bucketOffset
			}
		}
		bfs = append(bfs, bf)
		switch {
		case lex.isKeyword(")"):
			lex.nextToken()
			return bfs, nil
		case lex.isKeyword(","):
		default:
			return nil, fmt.Errorf("unexpected token: %q; expecting ',' or ')'", lex.token)
		}
	}
}

// tryParseBucketOffset tries parsing bucket offset, which can have the following formats:
//
// - integer number: 12345
// - floating-point number: 1.2345
// - duration: 1.5s - it is converted to nanoseconds
// - bytes: 1.5KiB
func tryParseBucketOffset(s string) (float64, bool) {
	// Try parsing s as floating point number
	if f, ok := tryParseFloat64(s); ok {
		return f, true
	}

	// Try parsing s as duration (1s, 5m, etc.)
	if nsecs, ok := tryParseDuration(s); ok {
		return float64(nsecs), true
	}

	// Try parsing s as bytes (KiB, MB, etc.)
	if n, ok := tryParseBytes(s); ok {
		return float64(n), true
	}

	return 0, false
}

// tryParseBucketSize tries parsing bucket size, which can have the following formats:
//
// - integer number: 12345
// - floating-point number: 1.2345
// - duration: 1.5s - it is converted to nanoseconds
// - bytes: 1.5KiB
// - ipv4 mask: /24
func tryParseBucketSize(s string) (float64, bool) {
	switch s {
	case "nanosecond":
		return 1, true
	case "microsecond":
		return nsecsPerMicrosecond, true
	case "millisecond":
		return nsecsPerMillisecond, true
	case "second":
		return nsecsPerSecond, true
	case "minute":
		return nsecsPerMinute, true
	case "hour":
		return nsecsPerHour, true
	case "day":
		return nsecsPerDay, true
	case "week":
		return nsecsPerWeek, true
	}

	// Try parsing s as floating point number
	if f, ok := tryParseFloat64(s); ok {
		return f, f > 0
	}

	// Try parsing s as duration (1s, 5m, etc.)
	if nsecs, ok := tryParseDuration(s); ok {
		return float64(nsecs), nsecs > 0
	}

	// Try parsing s as bytes (KiB, MB, etc.)
	if n, ok := tryParseBytes(s); ok {
		return float64(n), n > 0
	}

	if n, ok := tryParseIPv4Mask(s); ok {
		return float64(n), n > 0
	}

	return 0, false
}

func parseFieldNamesInParens(lex *lexer) ([]string, error) {
	fieldNames, err := parseFieldFiltersInParens(lex)
	if err != nil {
		return nil, err
	}
	for _, fieldName := range fieldNames {
		if prefixfilter.IsWildcardFilter(fieldName) {
			return nil, fmt.Errorf("the field name %q cannot end with '*'", fieldName)
		}
	}
	return fieldNames, nil
}

func parseFieldFiltersInParens(lex *lexer) ([]string, error) {
	if !lex.isKeyword("(") {
		return nil, fmt.Errorf("missing `(`")
	}
	var fields []string
	for {
		lex.nextToken()
		if lex.isKeyword(")") {
			lex.nextToken()
			return fields, nil
		}
		if lex.isKeyword(",") {
			return nil, fmt.Errorf("unexpected `,`")
		}
		field, err := parseFieldFilter(lex)
		if err != nil {
			return nil, err
		}
		fields = append(fields, field)
		switch {
		case lex.isKeyword(")"):
			lex.nextToken()
			return fields, nil
		case lex.isKeyword(","):
		default:
			return nil, fmt.Errorf("unexpected token: %q; expecting ',' or ')'", lex.token)
		}
	}
}

func parseFieldName(lex *lexer) (string, error) {
	fieldName, err := lex.nextCompoundToken()
	if err != nil {
		return "", err
	}
	fieldName = getCanonicalColumnName(fieldName)
	return fieldName, nil
}

func parseFieldFilter(lex *lexer) (string, error) {
	if lex.isKeyword("*") {
		lex.nextToken()
		return "*", nil
	}

	fieldName, err := lex.nextCompoundToken()
	if err != nil {
		return "", err
	}
	fieldName = getCanonicalColumnName(fieldName)
	if !lex.isSkippedSpace && lex.isKeyword("*") {
		lex.nextToken()
		fieldName += "*"
	}

	return fieldName, nil
}

func fieldNamesString(fields []string) string {
	a := make([]string, len(fields))
	for i, f := range fields {
		a[i] = quoteFieldFilterIfNeeded(f)
	}
	return strings.Join(a, ", ")
}
