package logstorage

import (
	"fmt"
	"strings"
	"sync"

	"github.com/VictoriaMetrics/VictoriaMetrics/lib/logger"

	"github.com/VictoriaMetrics/VictoriaLogs/lib/prefixfilter"
)

// PipeRunningStats processes '| running_stats ...' queries.
//
// See https://docs.victoriametrics.com/victorialogs/logsql/#running_stats-pipe
type PipeRunningStats struct {
	// if isTotal is set, then total stats must be calculated instead of running stats (aka `total_stats` pipe).
	isTotal bool

	// byFields contains field names with optional buckets from 'by(...)' clause.
	byFields []string

	// funcs contains stats functions to execute.
	funcs []PipeRunningStatsFunc
}

type PipeRunningStatsFunc struct {
	// f is stats function to execute
	f runningStatsFunc

	// resultName is the name of the output generated by f
	resultName string
}

type runningStatsFunc interface {
	// String returns string representation of runningStatsFunc
	String() string

	// updateNeededFields must update pf with the fields needed for calculating the given running stats
	updateNeededFields(pf *prefixfilter.Filter)
}

// ResultName returns the output field name for this function entry.
func (f *PipeRunningStatsFunc) ResultName() string {
	return f.resultName
}

// FuncString returns the full function string including arguments, e.g. "count()" or "sum(field)".
func (f *PipeRunningStatsFunc) FuncString() string {
	return f.f.String()
}

// FuncName returns the function name without arguments, e.g. "count" or "sum".
func (f *PipeRunningStatsFunc) FuncName() string {
	s := f.f.String()
	if idx := strings.IndexByte(s, '('); idx >= 0 {
		return s[:idx]
	}
	return s
}

func (ps *PipeRunningStats) String() string {
	s := "running_stats"
	if ps.isTotal {
		s = "total_stats"
	}

	if len(ps.byFields) > 0 {
		s += " by (" + fieldNamesString(ps.byFields) + ")"
	}

	funcs := ps.funcs
	if len(funcs) == 0 {
		logger.Panicf("BUG: pipeRunningStats must contain at least a single runningStatsFunc")
	}
	a := make([]string, len(funcs))

	for i, f := range funcs {
		a[i] = fmt.Sprintf("%s as %s", f.f.String(), quoteTokenIfNeeded(f.resultName))
	}
	s += " " + strings.Join(a, ", ")
	return s
}

func (ps *PipeRunningStats) Name() string {
	if ps.isTotal {
		return "total_stats"
	}
	return "running_stats"
}

// IsTotal returns true when the pipe is a total_stats pipe.
func (ps *PipeRunningStats) IsTotal() bool {
	return ps.isTotal
}

// ByFields returns the list of group-by field names.
func (ps *PipeRunningStats) ByFields() []string {
	return ps.byFields
}

// Funcs returns the list of running stats functions.
func (ps *PipeRunningStats) Funcs() []PipeRunningStatsFunc {
	return ps.funcs
}

func (ps *PipeRunningStats) updateNeededFields(pf *prefixfilter.Filter) {
	pfOrig := pf.Clone()

	for _, f := range ps.funcs {
		pf.AddDenyFilter(f.resultName)
		if pfOrig.MatchString(f.resultName) {
			f.f.updateNeededFields(pf)
		}
	}

	// byFields are needed unconditionally, since the output depends on them.
	for _, bf := range ps.byFields {
		pf.AddAllowFilter(bf)
	}
}

func (ps *PipeRunningStats) visitSubqueries(visitFunc func(q *Query)) {
	// nothing to do
}

func parsePipeRunningStats(lex *lexer) (pipe, error) {
	if !lex.isKeyword("running_stats") {
		return nil, fmt.Errorf("expecting `running_stats`; got %q", lex.token)
	}
	lex.nextToken()

	return parsePipeRunningStatsExt(lex, "running_stats")
}

func parsePipeRunningStatsExt(lex *lexer, pipeName string) (pipe, error) {
	var ps PipeRunningStats
	if pipeName == "total_stats" {
		ps.isTotal = true
	}

	if lex.isKeyword("by", "(") {
		if lex.isKeyword("by") {
			lex.nextToken()
		}
		bfs, err := parseFieldNamesInParens(lex)
		if err != nil {
			return nil, fmt.Errorf("cannot parse 'by' clause: %w", err)
		}
		ps.byFields = bfs
	}

	seenResultNames := make(map[string]runningStatsFunc)

	var funcs []PipeRunningStatsFunc
	for {
		var f PipeRunningStatsFunc

		sf, err := parseRunningStatsFunc(lex)
		if err != nil {
			return nil, err
		}
		f.f = sf

		resultName := ""
		if lex.isKeyword(",", "|", ")", "") {
			resultName = sf.String()
		} else {
			if lex.isKeyword("as") {
				lex.nextToken()
			}
			fieldName, err := parseFieldName(lex)
			if err != nil {
				return nil, fmt.Errorf("cannot parse result name for [%s]: %w", sf, err)
			}
			resultName = fieldName
		}
		if sfPrev := seenResultNames[resultName]; sfPrev != nil {
			return nil, fmt.Errorf("cannot use identical result name %q for [%s] and [%s]", resultName, sfPrev, sf)
		}
		seenResultNames[resultName] = sf
		f.resultName = resultName

		funcs = append(funcs, f)

		if lex.isKeyword("|", ")", "") {
			ps.funcs = funcs
			return &ps, nil
		}
		if !lex.isKeyword(",") {
			return nil, fmt.Errorf("unexpected token %q after [%s]; want ',', '|' or ')'", lex.token, sf)
		}
		lex.nextToken()
	}
}

func parseRunningStatsFunc(lex *lexer) (runningStatsFunc, error) {
	sps := getRunningStatsFuncParsers()
	for funcName, parserFunc := range sps {
		if !lex.isKeyword(funcName) {
			continue
		}
		sf, err := parserFunc(lex)
		if err != nil {
			return nil, fmt.Errorf("cannot parse %q func: %w", funcName, err)
		}
		return sf, nil
	}
	return nil, fmt.Errorf("unknown stats func %q", lex.token)
}

var runningStatsFuncParsers map[string]runningStatsFuncParser
var runningStatsFuncParsersOnce sync.Once

type runningStatsFuncParser func(lex *lexer) (runningStatsFunc, error)

func getRunningStatsFuncParsers() map[string]runningStatsFuncParser {
	runningStatsFuncParsersOnce.Do(initRunningStatsFuncParsers)
	return runningStatsFuncParsers
}

func initRunningStatsFuncParsers() {
	runningStatsFuncParsers = map[string]runningStatsFuncParser{
		"count": parseRunningStatsCount,
		"first": parseRunningStatsFirst,
		"last":  parseRunningStatsLast,
		"max":   parseRunningStatsMax,
		"min":   parseRunningStatsMin,
		"sum":   parseRunningStatsSum,
	}
}
