apiVersion: v2
name: victorialogs-aggregator
description: A Helm chart for VictoriaLogs Aggregator
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - victorialogs
  - aggregator
  - logging
maintainers:
  - name: k0rdent
