apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vlogxy.fullname" . }}-config
  labels:
    {{- include "vlogxy.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
    {{- toYaml .Values.config.data | nindent 4 }}
