{{- $secret_name := printf "%s-config" (include "vlogxy.fullname" .) }}
{{- $secret := lookup "v1" "Secret" $.Release.Namespace $secret_name }}
{{- $secret_key := .Values.config.fileName }}
{{- $secret_value := "" }}
{{- if $secret }}
  {{- $secret_value = index $secret.data $secret_key | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vlogxy.labels" . | nindent 4 }}
stringData:
  {{ $secret_key }}: {{ $secret_value | quote }}
type: Opaque
