apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vlogxy.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vlogxy.labels" . | nindent 4 }}
stringData:
  {{ .Values.config.fileName }}: |
    {{- toYaml .Values.config.data | nindent 4 }}
type: Opaque
