replicaCount: 1

image:
  registry: "ghcr.io/k0rdent"
  repository: vlogxy
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Configuration for the aggregator
config:
  # Path where config will be mounted in the pod
  mountPath: /etc/vlogxy
  # Config file name
  fileName: config.yaml
  # Configuration data
  data:
    server_groups:
      - cluster_name: "mothership"
        target: "kof-storage-victoria-logs-cluster-vlselect:9471"
        scheme: "http"
      - cluster_name: "andrejs-aws-ue2-istio"
        target: "andrejs-aws-ue2-istio1-vmauth:8427"
        path_prefix: "/vls"
        scheme: "http"
        http_client:
          basic_auth:
            username: "admin-70913480"
            password: "frGKngOma0MP3OVA"
