name: Test vlogxy

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release/*

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
      - name: Run Unit Tests
        run: make test